---
- name: Install bind-utils on client servers
  yum:
    name: bind-utils
    state: present
    update_cache: yes

- name: Disable SELinux
  selinux:
    state: disabled    

- name: Deploy resolv.conf for clients
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: inventory_hostname != "prdx-nsprimary101"

