---
- name: Install BIND (bypass broken dnf modules)
  command: >
    dnf install -y bind-utils --disablerepo=appstream
  args:
    creates: /usr/sbin/named
  become: yes

- name: Disable SELinux
  selinux:
    state: disabled    

- name: Deploy resolv.conf for clients
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: inventory_hostname != "prdx-nsprimary101"

